version: '3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn django_main.wsgi:application --bind 0.0.0.0:8000
    restart: "on-failure"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000

    env_file:
      - ./.env.prod
    depends_on:
      - db
    image: django_main
    links:
      - db:db
    networks:
      - postgres
      - djangonetwork
  db:
    container_name: pg_container
    image: postgres:15-alpine
    restart: "on-failure"
    env_file:
      - ./.env.prod.db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    networks:
      postgres:
        aliases:
          - db
    volumes:
      - postgres:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: "on-failure"
    env_file:
      - ./.env.pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      postgres:
        aliases:
          - pgadmin
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    links:
      - web:web
    restart: "on-failure"
    depends_on:
      - web
    networks:
      djangonetwork:
        aliases:
          - nginx

networks:
  postgres:
    driver: bridge
  djangonetwork:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  static_volume:
  media_volume:
